"""Pure, append-only P1 learning primitives for Polymarket Alpha."""

from .backfill import (
    BackfillFailureCode,
    PredictionBackfillFailure,
    PredictionBackfillInput,
    PredictionBackfillPlan,
    PredictionBackfillSuccess,
    ResolutionReference,
    ResolutionSelectionError,
    ResolutionSelectionPolicy,
    ResolutionSelectionReceipt,
    contracts_for_backfill_persistence,
    plan_prediction_backfill,
    select_resolution_head,
)
from .resolution import LearningResolutionError, build_market_resolution, build_prediction_resolution_link
from .resolution_intake import (
    RESOLUTION_INTAKE_VERSION,
    CapturedResolutionSource,
    ResolutionIntakeError,
    ResolutionIntakeRequest,
    ResolutionIntakeResult,
    intake_captured_resolution,
)
from .resolution_adapters import (
    RESOLUTION_ADAPTER_VERSION,
    CapturedOfficialResolution,
    OfficialJsonResolutionAdapter,
    OfficialKeyValueResolutionAdapter,
    ParsedResolutionAssertion,
    ResolutionAdapterError,
    ResolutionAdapterFailureCode,
    ResolutionSourceAdapter,
    ResolutionSourcePolicy,
    adapt_captured_official_resolution,
)
from .scoring import CalibrationPolicy, ScoringPolicy, build_calibration_report, score_prediction

__all__ = [
    "CalibrationPolicy",
    "BackfillFailureCode",
    "LearningResolutionError",
    "PredictionBackfillFailure",
    "PredictionBackfillInput",
    "PredictionBackfillPlan",
    "PredictionBackfillSuccess",
    "ResolutionReference",
    "RESOLUTION_INTAKE_VERSION",
    "RESOLUTION_ADAPTER_VERSION",
    "CapturedResolutionSource",
    "CapturedOfficialResolution",
    "ResolutionIntakeError",
    "ResolutionIntakeRequest",
    "ResolutionIntakeResult",
    "ResolutionAdapterError",
    "ResolutionAdapterFailureCode",
    "ResolutionSourceAdapter",
    "ResolutionSourcePolicy",
    "OfficialJsonResolutionAdapter",
    "OfficialKeyValueResolutionAdapter",
    "ParsedResolutionAssertion",
    "ResolutionSelectionError",
    "ResolutionSelectionPolicy",
    "ResolutionSelectionReceipt",
    "contracts_for_backfill_persistence",
    "ScoringPolicy",
    "build_calibration_report",
    "build_market_resolution",
    "build_prediction_resolution_link",
    "intake_captured_resolution",
    "adapt_captured_official_resolution",
    "plan_prediction_backfill",
    "select_resolution_head",
    "score_prediction",
]
