#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$ROOT/scripts/ops/weather_jrs_tmux_env.sh"
source "$ROOT/scripts/ops/weather_market_proxy_env.sh"
TMUX_SOCKET="$(weather_jrs_tmux_start_socket)"
PM_RUNTIME_ROOT="${WEATHER_PM_RUNTIME_ROOT:-$(weather_production_path "$ROOT" pm_runtime_root)}"
WEATHER_FEATURE_STORE_DIR="${WEATHER_FEATURE_STORE_DIR:-$(weather_production_path "$ROOT" feature_store_root)}"
export WEATHER_FEATURE_STORE_DIR
cd "$ROOT"

RUN_MODE="${1:-live}"
if [[ "$RUN_MODE" != "live" && "$RUN_MODE" != "--shadow" ]]; then
  echo "usage: $0 [--shadow]" >&2
  exit 2
fi
TMUX_SESSION="${LOW_PRICE_YES_LOTTERY_TMUX_SESSION:-low_price_yes_lottery_${RUN_MODE#--}_v1}"

RUNTIME_DIR="${LOW_PRICE_YES_LOTTERY_RUNTIME_DIR:-$PM_RUNTIME_ROOT/weather_edge_v1/low_price_yes_lottery_tiny_live_v1}"
PID_FILE="$RUNTIME_DIR/loop.pid"
LOG_FILE="$RUNTIME_DIR/loop.log"
mkdir -p "$RUNTIME_DIR" "$PM_RUNTIME_ROOT/weather_edge_v1/live"

if [[ "${LOW_PRICE_YES_LOTTERY_LOOP_CHILD:-0}" != "1" && -s "$PID_FILE" ]]; then
  old_pid="$(cat "$PID_FILE")"
  if [[ "$old_pid" == "tmux:$TMUX_SESSION" ]] && weather_jrs_tmux "$TMUX_SOCKET" has-session -t "$TMUX_SESSION" 2>/dev/null; then
    echo "already_running session=$TMUX_SESSION socket=$TMUX_SOCKET log=$LOG_FILE"
    exit 0
  elif [[ "$old_pid" =~ ^[0-9]+$ ]] && kill -0 "$old_pid" 2>/dev/null; then
    echo "already_running pid=$old_pid log=$LOG_FILE"
    exit 0
  fi
fi

PYTHON_BIN="${PYTHON_BIN:-.venv/bin/python}"
if [[ ! -x "$PYTHON_BIN" ]]; then
  PYTHON_BIN="python3"
fi

LOW_PRICE_YES_LOTTERY_LIVE="${LOW_PRICE_YES_LOTTERY_LIVE:-1}"
LOW_PRICE_YES_LOTTERY_CONFIRM_LIVE="${LOW_PRICE_YES_LOTTERY_CONFIRM_LIVE:-1}"
LOW_PRICE_YES_LOTTERY_NOTIONAL="${LOW_PRICE_YES_LOTTERY_NOTIONAL:-0.8}"
LOW_PRICE_YES_LOTTERY_SIZING_POLICY="${LOW_PRICE_YES_LOTTERY_SIZING_POLICY:-fixed_5_shares}"
LOW_PRICE_YES_LOTTERY_MAKER_FIRST_FRACTION="${LOW_PRICE_YES_LOTTERY_MAKER_FIRST_FRACTION:-1.0}"
LOW_PRICE_YES_LOTTERY_TAKER_FALLBACK_MIN_NOTIONAL_USD="${LOW_PRICE_YES_LOTTERY_TAKER_FALLBACK_MIN_NOTIONAL_USD:-1.0}"
LOW_PRICE_YES_LOTTERY_INTERVAL_SECONDS="${LOW_PRICE_YES_LOTTERY_INTERVAL_SECONDS:-300}"
LOW_PRICE_YES_LOTTERY_MIN_ASK="${LOW_PRICE_YES_LOTTERY_MIN_ASK:-0.05}"
LOW_PRICE_YES_LOTTERY_MAX_ASK="${LOW_PRICE_YES_LOTTERY_MAX_ASK:-0.20}"
LOW_PRICE_YES_LOTTERY_MIN_EDGE="${LOW_PRICE_YES_LOTTERY_MIN_EDGE:-0.20}"
LOW_PRICE_YES_LOTTERY_MAX_TAKER_CUSHION="${LOW_PRICE_YES_LOTTERY_MAX_TAKER_CUSHION:-0.01}"
LOW_PRICE_YES_LOTTERY_MIN_FEE_EDGE="${LOW_PRICE_YES_LOTTERY_MIN_FEE_EDGE:-0.15}"
LOW_PRICE_YES_LOTTERY_SNAPSHOT_DIR="${LOW_PRICE_YES_LOTTERY_SNAPSHOT_DIR:-$(weather_production_path "$ROOT" strategy_paper_snapshot_dir)}"
LOW_PRICE_YES_LOTTERY_MAX_WEATHER_SNAPSHOT_AGE_MIN="${LOW_PRICE_YES_LOTTERY_MAX_WEATHER_SNAPSHOT_AGE_MIN:-30}"
LOW_PRICE_YES_LOTTERY_MAX_SNAPSHOT_AGE_HOURS="${LOW_PRICE_YES_LOTTERY_MAX_SNAPSHOT_AGE_HOURS:-0.5}"
LOW_PRICE_YES_LOTTERY_MIN_HOURS_TO_SETTLE="${LOW_PRICE_YES_LOTTERY_MIN_HOURS_TO_SETTLE:-22}"
LOW_PRICE_YES_LOTTERY_MAX_HOURS_TO_SETTLE="${LOW_PRICE_YES_LOTTERY_MAX_HOURS_TO_SETTLE:-24}"
LOW_PRICE_YES_LOTTERY_MAX_CANDIDATES="${LOW_PRICE_YES_LOTTERY_MAX_CANDIDATES:-80}"
LOW_PRICE_YES_LOTTERY_BOOK_TIMEOUT_SECONDS="${LOW_PRICE_YES_LOTTERY_BOOK_TIMEOUT_SECONDS:-10}"
LOW_PRICE_YES_LOTTERY_BOOK_RETRIES="${LOW_PRICE_YES_LOTTERY_BOOK_RETRIES:-1}"
LOW_PRICE_YES_LOTTERY_TOKEN_TIMEOUT_SECONDS="${LOW_PRICE_YES_LOTTERY_TOKEN_TIMEOUT_SECONDS:-15}"
LOW_PRICE_YES_LOTTERY_TAKER_FEE_RATE="${LOW_PRICE_YES_LOTTERY_TAKER_FEE_RATE:-0.05}"
LOW_PRICE_YES_LOTTERY_MAKER_REBATE_RATE="${LOW_PRICE_YES_LOTTERY_MAKER_REBATE_RATE:-0}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_ENABLED="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_ENABLED:-1}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_REFRESH_TTL_MIN="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_REFRESH_TTL_MIN:-15}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_TAKER_TTL_MIN="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_TAKER_TTL_MIN:-30}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_SPREAD_CAP="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_SPREAD_CAP:-0.01}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_TAKER_MAX_PREMIUM="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_TAKER_MAX_PREMIUM:-0}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_REPRICE_CUSHION="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_REPRICE_CUSHION:-0.20}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_DOWNSHIFT_MIN="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_DOWNSHIFT_MIN:-0.01}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_MIN_REPRICE_IMPROVEMENT="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_MIN_REPRICE_IMPROVEMENT:-0.001}"
LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_MAX_ACTIONS="${LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_MAX_ACTIONS:-3}"
LOW_PRICE_YES_LOTTERY_DISABLE_LIVE_TOKEN_RESOLUTION="${LOW_PRICE_YES_LOTTERY_DISABLE_LIVE_TOKEN_RESOLUTION:-0}"
LOW_PRICE_YES_LOTTERY_NO_TELEGRAM="${LOW_PRICE_YES_LOTTERY_NO_TELEGRAM:-0}"
POLYMARKET_GAMMA_TIMEOUT_SEC="${POLYMARKET_GAMMA_TIMEOUT_SEC:-3}"
POLYMARKET_GAMMA_RETRIES="${POLYMARKET_GAMMA_RETRIES:-0}"
export POLYMARKET_GAMMA_TIMEOUT_SEC POLYMARKET_GAMMA_RETRIES

if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
fi

if [[ "$RUN_MODE" == "--shadow" ]]; then
  LOW_PRICE_YES_LOTTERY_LIVE=0
  LOW_PRICE_YES_LOTTERY_CONFIRM_LIVE=0
  LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_ENABLED=0
  LOW_PRICE_YES_LOTTERY_NO_TELEGRAM=1
fi

LOW_PRICE_YES_LOTTERY_MARKET_PROXY="${LOW_PRICE_YES_LOTTERY_MARKET_PROXY:-${WEATHER_DATA_FEED_MARKET_PROXY:-http://127.0.0.1:7890}}"
export LOW_PRICE_YES_LOTTERY_MARKET_PROXY
weather_export_market_proxy_env "$LOW_PRICE_YES_LOTTERY_MARKET_PROXY"

args=(
  scripts/ops/low_price_yes_lottery_tiny_live.py
  loop
  --snapshot-dir "$LOW_PRICE_YES_LOTTERY_SNAPSHOT_DIR"
  --max-weather-snapshot-age-min "$LOW_PRICE_YES_LOTTERY_MAX_WEATHER_SNAPSHOT_AGE_MIN"
  --order-notional-usd "$LOW_PRICE_YES_LOTTERY_NOTIONAL"
  --sizing-policy "$LOW_PRICE_YES_LOTTERY_SIZING_POLICY"
  --maker-first-fraction "$LOW_PRICE_YES_LOTTERY_MAKER_FIRST_FRACTION"
  --taker-fallback-min-notional-usd "$LOW_PRICE_YES_LOTTERY_TAKER_FALLBACK_MIN_NOTIONAL_USD"
  --interval-seconds "$LOW_PRICE_YES_LOTTERY_INTERVAL_SECONDS"
  --min-ask "$LOW_PRICE_YES_LOTTERY_MIN_ASK"
  --max-ask "$LOW_PRICE_YES_LOTTERY_MAX_ASK"
  --min-edge "$LOW_PRICE_YES_LOTTERY_MIN_EDGE"
  --max-taker-cushion "$LOW_PRICE_YES_LOTTERY_MAX_TAKER_CUSHION"
  --min-fee-adjusted-edge "$LOW_PRICE_YES_LOTTERY_MIN_FEE_EDGE"
  --max-decision-snapshot-age-hours "$LOW_PRICE_YES_LOTTERY_MAX_SNAPSHOT_AGE_HOURS"
  --min-decision-hours-to-settle "$LOW_PRICE_YES_LOTTERY_MIN_HOURS_TO_SETTLE"
  --max-decision-hours-to-settle "$LOW_PRICE_YES_LOTTERY_MAX_HOURS_TO_SETTLE"
  --max-candidates-per-run "$LOW_PRICE_YES_LOTTERY_MAX_CANDIDATES"
  --book-timeout-sec "$LOW_PRICE_YES_LOTTERY_BOOK_TIMEOUT_SECONDS"
  --book-retries "$LOW_PRICE_YES_LOTTERY_BOOK_RETRIES"
  --book-failover-on-timeout
  --token-resolution-timeout-sec "$LOW_PRICE_YES_LOTTERY_TOKEN_TIMEOUT_SECONDS"
  --taker-fee-rate "$LOW_PRICE_YES_LOTTERY_TAKER_FEE_RATE"
  --maker-rebate-rate "$LOW_PRICE_YES_LOTTERY_MAKER_REBATE_RATE"
)

if [[ -n "${LOW_PRICE_YES_LOTTERY_MIN_EVENT_DATE:-}" ]]; then
  args+=(--min-event-date "$LOW_PRICE_YES_LOTTERY_MIN_EVENT_DATE")
fi
if [[ -n "${LOW_PRICE_YES_LOTTERY_MAX_EVENT_DATE:-}" ]]; then
  args+=(--max-event-date "$LOW_PRICE_YES_LOTTERY_MAX_EVENT_DATE")
fi
if [[ "$LOW_PRICE_YES_LOTTERY_LIVE" == "1" ]]; then
  args+=(--live)
fi
if [[ "$LOW_PRICE_YES_LOTTERY_CONFIRM_LIVE" == "1" ]]; then
  args+=(--confirm-live)
fi
if [[ "$LOW_PRICE_YES_LOTTERY_NO_TELEGRAM" == "1" ]]; then
  args+=(--no-telegram)
fi
if [[ "$LOW_PRICE_YES_LOTTERY_DISABLE_LIVE_TOKEN_RESOLUTION" == "1" ]]; then
  args+=(--disable-live-token-resolution)
fi
if [[ "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_ENABLED" == "1" ]]; then
  args+=(
    --maker-lifecycle-enabled
    --maker-lifecycle-refresh-ttl-min "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_REFRESH_TTL_MIN"
    --maker-lifecycle-taker-ttl-min "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_TAKER_TTL_MIN"
    --maker-lifecycle-spread-cap "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_SPREAD_CAP"
    --maker-lifecycle-taker-max-premium "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_TAKER_MAX_PREMIUM"
    --maker-lifecycle-reprice-cushion "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_REPRICE_CUSHION"
    --maker-lifecycle-downshift-min "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_DOWNSHIFT_MIN"
    --maker-lifecycle-min-reprice-improvement "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_MIN_REPRICE_IMPROVEMENT"
    --maker-lifecycle-max-actions-per-run "$LOW_PRICE_YES_LOTTERY_MAKER_LIFECYCLE_MAX_ACTIONS"
  )
fi

if [[ "${LOW_PRICE_YES_LOTTERY_LOOP_CHILD:-0}" != "1" ]]; then
  date -u +"[low_price_yes_lottery] loop_start_utc=%Y-%m-%dT%H:%M:%SZ sizing=$LOW_PRICE_YES_LOTTERY_SIZING_POLICY cash_ref=$LOW_PRICE_YES_LOTTERY_NOTIONAL live=$LOW_PRICE_YES_LOTTERY_LIVE proxy=$LOW_PRICE_YES_LOTTERY_MARKET_PROXY" >>"$LOG_FILE"
  weather_jrs_tmux "$TMUX_SOCKET" kill-session -t "$TMUX_SESSION" 2>/dev/null || true
  launch_cmd=(env \
    LOW_PRICE_YES_LOTTERY_LOOP_CHILD=1 \
    LOW_PRICE_YES_LOTTERY_RUNTIME_DIR="$RUNTIME_DIR" \
    LOW_PRICE_YES_LOTTERY_MARKET_PROXY="$LOW_PRICE_YES_LOTTERY_MARKET_PROXY" \
    WEATHER_RUNTIME_CODE_COMMIT="${WEATHER_RUNTIME_CODE_COMMIT:-committed_checkout}" \
    POLYMARKET_GAMMA_TIMEOUT_SEC="$POLYMARKET_GAMMA_TIMEOUT_SEC" \
    POLYMARKET_GAMMA_RETRIES="$POLYMARKET_GAMMA_RETRIES" \
    "$PYTHON_BIN" -u "${args[@]}")
  printf -v quoted_launch_cmd '%q ' "${launch_cmd[@]}"
  weather_jrs_tmux "$TMUX_SOCKET" new-session -d -s "$TMUX_SESSION" \
    "cd $(printf '%q' "$ROOT") && exec $quoted_launch_cmd >> $(printf '%q' "$LOG_FILE") 2>&1"
  echo "tmux:$TMUX_SESSION" >"$PID_FILE"
  echo "started low-price YES lottery socket=$TMUX_SOCKET session=$TMUX_SESSION log=$LOG_FILE sizing=$LOW_PRICE_YES_LOTTERY_SIZING_POLICY cash_ref=$LOW_PRICE_YES_LOTTERY_NOTIONAL ask=${LOW_PRICE_YES_LOTTERY_MIN_ASK}-${LOW_PRICE_YES_LOTTERY_MAX_ASK} edge=$LOW_PRICE_YES_LOTTERY_MIN_EDGE live=$LOW_PRICE_YES_LOTTERY_LIVE"
  exit 0
fi

echo "$$" >"$PID_FILE"
trap 'rm -f "$PID_FILE"' EXIT
date -u +"[low_price_yes_lottery] loop_start_utc=%Y-%m-%dT%H:%M:%SZ pid=$$ sizing=$LOW_PRICE_YES_LOTTERY_SIZING_POLICY cash_ref=$LOW_PRICE_YES_LOTTERY_NOTIONAL live=$LOW_PRICE_YES_LOTTERY_LIVE proxy=$LOW_PRICE_YES_LOTTERY_MARKET_PROXY"
"$PYTHON_BIN" -u "${args[@]}"
