#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
source "$PROJECT_DIR/scripts/ops/weather_jrs_tmux_env.sh"
SERVICE_DIR="${WEATHER_DATA_FEED_SERVICE_DIR:-$PROJECT_DIR}"
RUNTIME_ROOT="${WEATHER_DATA_FEED_RUNTIME_ROOT:-$(weather_production_path "$PROJECT_DIR" data_feed_runtime_root)}"
MARKET_BOOKS_ROOT="${WEATHER_MARKET_BOOKS_ROOT:-$(weather_production_path "$PROJECT_DIR" market_books_root)}"
MARKET_LADDER_ROOT="${WEATHER_MARKET_LADDER_ROOT:-$(weather_production_path "$PROJECT_DIR" market_ladder_snapshot_root)}"
CACHE_ROOT="${WEATHER_DATA_FEED_CACHE_ROOT:-$RUNTIME_ROOT/cache}"
OBSERVATION_CACHE="${WEATHER_OBSERVATION_CACHE:-$(weather_production_path "$PROJECT_DIR" observation_cache_path)}"
INTERVAL_SEC="${WEATHER_MARKET_BOOKS_INTERVAL_SEC:-300}"
ORDERBOOK_BUDGET_SEC="${WEATHER_MARKET_BOOKS_BUDGET_SEC:-240}"
SOURCE_MAX_AGE_SEC="${WEATHER_MARKET_BOOKS_SOURCE_MAX_AGE_SEC:-420}"
TMUX_SOCKET="$(weather_jrs_tmux_start_socket "$RUNTIME_ROOT")"
TMUX_SESSION="${WEATHER_MARKET_BOOKS_TMUX_SESSION:-weather_market_books}"
LOG_FILE="${WEATHER_MARKET_BOOKS_LOG_FILE:-$RUNTIME_ROOT/market_books/collector.log}"
WS_OUTPUT_ROOT="${WEATHER_MARKET_BOOKS_WS_OUTPUT_ROOT:-$MARKET_BOOKS_ROOT/ws_incremental}"
WS_HEALTH_PATH="${WEATHER_MARKET_BOOKS_WS_HEALTH_PATH:-$MARKET_BOOKS_ROOT/collector_health.json}"
WS_LOG_FILE="${WEATHER_MARKET_BOOKS_WS_LOG_FILE:-$MARKET_BOOKS_ROOT/ws_collector.log}"
WS_SOURCE_EVENTS="${WEATHER_MARKET_BOOKS_WS_SOURCE_EVENTS:-$RUNTIME_ROOT/output/source_events}"
WS_CITIES="${WEATHER_MARKET_BOOKS_WS_CITIES:-Amsterdam Tokyo Helsinki Busan}"
WS_ACTIVE_BRACKET_COUNT="${WEATHER_MARKET_BOOKS_WS_ACTIVE_BRACKET_COUNT:-2}"
WS_RESEARCH_BRACKET_COUNT="${WEATHER_MARKET_BOOKS_WS_RESEARCH_BRACKET_COUNT:-3}"
WS_EVENT_BRACKET_COUNT="${WEATHER_MARKET_BOOKS_WS_EVENT_BRACKET_COUNT:-3}"
WS_POST_INVALIDATION_SEC="${WEATHER_MARKET_BOOKS_WS_POST_INVALIDATION_SEC:-0}"
WS_EVENT_BURST_SEC="${WEATHER_MARKET_BOOKS_WS_EVENT_BURST_SEC:-120}"
WS_REPORT_WINDOW_BEFORE_SEC="${WEATHER_MARKET_BOOKS_WS_REPORT_WINDOW_BEFORE_SEC:-45}"
WS_REPORT_WINDOW_AFTER_SEC="${WEATHER_MARKET_BOOKS_WS_REPORT_WINDOW_AFTER_SEC:-120}"
WS_RESEARCH_WINDOW_BEFORE_SEC="${WEATHER_MARKET_BOOKS_WS_RESEARCH_WINDOW_BEFORE_SEC:-125}"
WS_RESEARCH_SAMPLE_MODULUS="${WEATHER_MARKET_BOOKS_WS_RESEARCH_SAMPLE_MODULUS:-6}"
WS_DAILY_PAYLOAD_BUDGET_BYTES="${WEATHER_MARKET_BOOKS_WS_DAILY_PAYLOAD_BUDGET_BYTES:-3000000000}"
STARTED_EPOCH="$(date +%s)"

if weather_jrs_tmux "$TMUX_SOCKET" has-session -t "$TMUX_SESSION" 2>/dev/null; then
  echo "already running: tmux_socket=$TMUX_SOCKET session=$TMUX_SESSION"
  exit 0
fi

weather_jrs_tmux "$TMUX_SOCKET" new-session -d -s "$TMUX_SESSION" \
  "export WEATHER_DATA_FEED_SERVICE_DIR='$SERVICE_DIR' \
     WEATHER_DATA_FEED_RUNTIME_ROOT='$RUNTIME_ROOT' \
     WEATHER_MARKET_BOOKS_ROOT='$MARKET_BOOKS_ROOT' \
     WEATHER_MARKET_LADDER_ROOT='$MARKET_LADDER_ROOT' \
     WEATHER_DATA_FEED_CACHE_ROOT='$CACHE_ROOT' \
     WEATHER_OBSERVATION_CACHE='$OBSERVATION_CACHE' \
     WEATHER_MARKET_BOOKS_INTERVAL_SEC='$INTERVAL_SEC' \
     WEATHER_MARKET_BOOKS_BUDGET_SEC='$ORDERBOOK_BUDGET_SEC' \
     WEATHER_MARKET_BOOKS_SOURCE_MAX_AGE_SEC='$SOURCE_MAX_AGE_SEC' \
     WEATHER_MARKET_BOOKS_LOG_FILE='$LOG_FILE' \
   && exec bash '$PROJECT_DIR/scripts/ops/_weather_market_books_loop_body.sh'"

if ! weather_jrs_tmux "$TMUX_SOCKET" new-window -d -t "=$TMUX_SESSION" -n ws \
  "export WEATHER_DATA_FEED_SERVICE_DIR='$SERVICE_DIR' \
     WEATHER_MARKET_BOOKS_ROOT='$MARKET_BOOKS_ROOT' \
     WEATHER_OBSERVATION_CACHE='$OBSERVATION_CACHE' \
     WEATHER_MARKET_BOOKS_WS_OUTPUT_ROOT='$WS_OUTPUT_ROOT' \
     WEATHER_MARKET_BOOKS_WS_HEALTH_PATH='$WS_HEALTH_PATH' \
     WEATHER_MARKET_BOOKS_WS_LOG_FILE='$WS_LOG_FILE' \
     WEATHER_MARKET_BOOKS_WS_SOURCE_EVENTS='$WS_SOURCE_EVENTS' \
     WEATHER_MARKET_BOOKS_WS_CITIES='$WS_CITIES' \
     WEATHER_MARKET_BOOKS_WS_ACTIVE_BRACKET_COUNT='$WS_ACTIVE_BRACKET_COUNT' \
     WEATHER_MARKET_BOOKS_WS_RESEARCH_BRACKET_COUNT='$WS_RESEARCH_BRACKET_COUNT' \
     WEATHER_MARKET_BOOKS_WS_EVENT_BRACKET_COUNT='$WS_EVENT_BRACKET_COUNT' \
     WEATHER_MARKET_BOOKS_WS_POST_INVALIDATION_SEC='$WS_POST_INVALIDATION_SEC' \
     WEATHER_MARKET_BOOKS_WS_EVENT_BURST_SEC='$WS_EVENT_BURST_SEC' \
     WEATHER_MARKET_BOOKS_WS_REPORT_WINDOW_BEFORE_SEC='$WS_REPORT_WINDOW_BEFORE_SEC' \
     WEATHER_MARKET_BOOKS_WS_REPORT_WINDOW_AFTER_SEC='$WS_REPORT_WINDOW_AFTER_SEC' \
     WEATHER_MARKET_BOOKS_WS_RESEARCH_WINDOW_BEFORE_SEC='$WS_RESEARCH_WINDOW_BEFORE_SEC' \
     WEATHER_MARKET_BOOKS_WS_RESEARCH_SAMPLE_MODULUS='$WS_RESEARCH_SAMPLE_MODULUS' \
     WEATHER_MARKET_BOOKS_WS_DAILY_PAYLOAD_BUDGET_BYTES='$WS_DAILY_PAYLOAD_BUDGET_BYTES' \
   && exec bash '$PROJECT_DIR/scripts/ops/_weather_market_books_ws_body.sh'"
then
  weather_jrs_tmux "$TMUX_SOCKET" kill-session -t "=$TMUX_SESSION" 2>/dev/null || true
  exit 1
fi

for _ in {1..20}; do
  weather_jrs_tmux "$TMUX_SOCKET" has-session -t "$TMUX_SESSION" 2>/dev/null || exit 1
  if "$PROJECT_DIR/.venv/bin/python" - "$WS_HEALTH_PATH" "$STARTED_EPOCH" <<'PY'
import json
import os
import sys

path, started_epoch = sys.argv[1], int(sys.argv[2])
try:
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
except (OSError, ValueError):
    raise SystemExit(1)
fresh = os.path.getmtime(path) >= started_epoch
raise SystemExit(0 if fresh and payload.get("status") == "ok" else 1)
PY
  then
    break
  fi
  sleep 1
done
"$PROJECT_DIR/.venv/bin/python" - "$WS_HEALTH_PATH" "$STARTED_EPOCH" <<'PY'
import json
import os
import sys

path, started_epoch = sys.argv[1], int(sys.argv[2])
with open(path, encoding="utf-8") as handle:
    payload = json.load(handle)
assert os.path.getmtime(path) >= started_epoch, "WebSocket health was not refreshed"
assert payload.get("status") == "ok", payload
PY
echo "started tmux_socket=$TMUX_SOCKET session=$TMUX_SESSION log=$LOG_FILE ws_health=$WS_HEALTH_PATH"
