"""Ingest settlements directly from pm_history/*.json files.

Why a dedicated path
--------------------
The legacy pipeline routed settlements through `t24_paper_ledger_trades.csv`
(see legacy_migration.research_csv). That CSV is regenerated by
`settle_t24_paper.py --source ledger` on N100 and the regeneration is not on
a timer -- it's been stale since 2026-05-17. Meanwhile `cache/pm_history/*.json`
on N100 is refreshed every day by the production daily_pipeline and stays
current modulo the known Polymarket gaps (chronic null cities + 5/17 partial
+ 5/18 full outage).

This ingest reads pm_history directly so the settlements table stays current
without depending on the derived CSV refresh.

Schema mapping
--------------
pm_history file `City_2026-05-NN.json`:
    { "unit": "C", "brackets": [
        { "label": "20", "final_price": 1.0, "token_id": "...", "closed": true,
          "question": "Will the highest temperature in ..." },
        ...
    ] }

Settlement rows (canonical schema):
    settlement_id, target_date, condition_id, market_id, bracket, token_id,
    final_price, settlement_status

Settlement outcome rows (source-grain schema):
    source_system, city, target_date, bracket, condition_id, market_id,
    token_id, raw_final_price, final_price, settlement_status, source_path

Files with `null` content or empty `brackets` are skipped (genuine upstream
gaps). For each bracket, condition_id and market_id are looked up from the
`signals` table by (city, target_date, bracket) -- the same market the
strategy was trading. Settlements with no signal row get `condition_id=NULL`
and won't join in trade queries. `settlement_outcomes` still preserves the
city/date/bracket truth for basket research and later condition-id enrichment.

Idempotent: re-running is safe.

Run:
    python -m weather_dashboard.ingest.pm_history_settlements --db-path runtime/weather.db
    python -m weather_dashboard.ingest.pm_history_settlements --db-path runtime/weather.db --pmh-dir <path>
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from datetime import date as calendar_date
from datetime import datetime, timedelta, timezone
from pathlib import Path

from src.strategies.weather_edge_v1.ids import make_settlement_id
from weather_dashboard.ingest.settlement_outcomes import (
    ensure_settlement_outcomes_schema,
    insert_settlement_outcome,
    normalize_final_price,
    outcome_from_pm_history_bracket,
    parse_pm_history_filename,
    settlement_status as outcome_settlement_status,
    stored_final_price,
)
from weather_data_feed.source_lineage import producer_build_id

DEFAULT_PMH_DIR = "runtime/weather_edge_v1/market_data/cache/pm_history"


def _settlement_id(
    target_date: str,
    condition_id: str | None,
    market_id: str | None,
    bracket: str,
) -> str:
    if condition_id and market_id:
        # Keep the same natural ID as legacy_migration.research_csv so a
        # pm_history backfill does not duplicate an already-migrated settlement.
        return make_settlement_id(
            target_date=target_date,
            condition_id=condition_id,
            market_id=market_id,
            bracket=bracket,
        )
    raw = f"pm_history_settlement|{target_date}|{condition_id or ''}|{market_id or ''}|{bracket}"
    import hashlib
    return hashlib.sha256(raw.encode()).hexdigest()


def _binary_final_price(final_price) -> float | None:
    """Normalize Polymarket near-binary settlement prices.

    Some pm_history files store resolved brackets as 0.9995 / 0.0005 while
    the downstream settlement contract expects binary 1.0 / 0.0.
    """
    return normalize_final_price(final_price)


def _settlement_status(final_price) -> str:
    return outcome_settlement_status(final_price)


def _parse_filename(name: str) -> tuple[str, str] | None:
    """`Beijing_2026-05-20.json` -> ('Beijing', '2026-05-20'). Skips others."""
    return parse_pm_history_filename(name)


def _signal_lookup_map(
    conn: sqlite3.Connection,
    *,
    start_date: str | None = None,
    end_date: str | None = None,
) -> dict[tuple, tuple[str, str]]:
    """(city, target_date, bracket) -> (condition_id, market_id) from signals.
    Brackets the strategy never touched won't be in this map; their settlement
    is still written but with NULL condition_id.
    """
    clauses = ["condition_id IS NOT NULL"]
    params: list[str] = []
    if start_date:
        clauses.append("target_date >= ?")
        params.append(start_date)
    if end_date:
        clauses.append("target_date <= ?")
        params.append(end_date)

    out: dict[tuple, tuple[str, str]] = {}
    for r in conn.execute(
        "SELECT DISTINCT city, target_date, bracket, condition_id, market_id "
        f"FROM signals WHERE {' AND '.join(clauses)}",
        params,
    ):
        out[(r["city"], r["target_date"], str(r["bracket"]))] = (
            r["condition_id"], r["market_id"]
        )
    return out


def ingest(
    conn: sqlite3.Connection,
    pmh_dir: str,
    *,
    dry_run: bool = False,
    start_date: str | None = None,
    end_date: str | None = None,
    cities: list[str] | None = None,
) -> dict:
    conn.row_factory = sqlite3.Row
    ensure_settlement_outcomes_schema(conn)
    sig_lookup = _signal_lookup_map(
        conn,
        start_date=start_date,
        end_date=end_date,
    )
    files: list[Path] = []
    pmh_root = Path(pmh_dir)
    if cities and start_date and end_date:
        current = calendar_date.fromisoformat(start_date)
        final = calendar_date.fromisoformat(end_date)
        while current <= final:
            target_date = current.isoformat()
            for city in sorted(set(cities)):
                path = pmh_root / f"{city}_{target_date}.json"
                if path.exists():
                    files.append(path)
            current += timedelta(days=1)
    else:
        # Path.glob() stats every matching directory entry.  The production
        # cache contains years of city-day files on an external volume, so
        # filter names before doing any per-file I/O.
        for path in sorted(pmh_root.iterdir(), key=lambda item: item.name):
            if "_2026-" not in path.name or path.suffix != ".json":
                continue
            parsed = _parse_filename(path.name)
            if parsed is None:
                continue
            _, target_date = parsed
            if start_date and target_date < start_date:
                continue
            if end_date and target_date > end_date:
                continue
            files.append(path)

    stats = {
        "files_seen": 0, "files_skipped_null": 0,
        "brackets_seen": 0, "settlements_inserted": 0,
        "settlement_outcomes_inserted": 0,
        "no_signal_match": 0, "dry_run": dry_run,
        "start_date": start_date, "end_date": end_date,
    }
    build_id, _ = producer_build_id()

    for f in files:
        parsed = _parse_filename(f.name)
        if parsed is None:
            continue
        city, date = parsed
        stats["files_seen"] += 1
        try:
            raw_bytes = f.read_bytes()
            d = json.loads(raw_bytes)
        except Exception:
            stats["files_skipped_null"] += 1
            continue
        source_payload_hash = hashlib.sha256(raw_bytes).hexdigest()
        source_file_mtime_utc = datetime.fromtimestamp(
            f.stat().st_mtime, tz=timezone.utc
        ).isoformat()
        canonical_available_at_utc = datetime.now(timezone.utc).isoformat()
        if not isinstance(d, dict) or not d.get("brackets"):
            stats["files_skipped_null"] += 1
            continue

        for b in d["brackets"]:
            label = str(b.get("label"))
            final_price = b.get("final_price")
            token_id = str(b.get("token_id") or "") or None
            if final_price is None:
                continue
            stats["brackets_seen"] += 1
            condition_id, market_id = sig_lookup.get((city, date, label), (None, None))
            if condition_id is None:
                stats["no_signal_match"] += 1
            sid = _settlement_id(date, condition_id, market_id, label)
            status = _settlement_status(final_price)

            if dry_run:
                continue
            outcome = outcome_from_pm_history_bracket(
                source_path=f,
                city=city,
                target_date=date,
                unit=d.get("unit"),
                bracket=b,
                condition_id=condition_id,
                market_id=market_id,
                source_payload_hash=source_payload_hash,
                source_file_mtime_utc=source_file_mtime_utc,
                available_at_utc=canonical_available_at_utc,
                producer_build=build_id,
            )
            if outcome:
                stats["settlement_outcomes_inserted"] += insert_settlement_outcome(conn, outcome)
            cur = conn.execute(
                """INSERT OR IGNORE INTO settlements
                   (settlement_id, target_date, condition_id, market_id, bracket,
                    token_id, final_price, settlement_status)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (sid, date, condition_id, market_id, label, token_id, stored_final_price(final_price), status),
            )
            stats["settlements_inserted"] += cur.rowcount or 0

    if not dry_run:
        conn.commit()
    return stats


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db-path", default="runtime/weather.db")
    ap.add_argument("--pmh-dir", default=DEFAULT_PMH_DIR)
    ap.add_argument("--start-date")
    ap.add_argument("--end-date")
    ap.add_argument("--city", action="append", dest="cities")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    conn = sqlite3.connect(args.db_path)
    try:
        out = ingest(
            conn,
            args.pmh_dir,
            dry_run=args.dry_run,
            start_date=args.start_date,
            end_date=args.end_date,
            cities=args.cities,
        )
        print(json.dumps(out, indent=2))
    finally:
        conn.close()


if __name__ == "__main__":
    main()
