"""Ingest settlements directly from pm_history/*.json files.

Why a dedicated path
--------------------
The legacy pipeline routed settlements through `t24_paper_ledger_trades.csv`
(see legacy_migration.research_csv). That CSV is regenerated by
`settle_t24_paper.py --source ledger` on N100 and the regeneration is not on
a timer -- it's been stale since 2026-05-17. Meanwhile `cache/pm_history/*.json`
on N100 is refreshed every day by the production daily_pipeline and stays
current modulo the known Polymarket gaps (chronic null cities + 5/17 partial
+ 5/18 full outage).

This ingest reads pm_history directly so the settlements table stays current
without depending on the derived CSV refresh.

Schema mapping
--------------
pm_history file `City_2026-05-NN.json`:
    { "unit": "C", "brackets": [
        { "label": "20", "final_price": 1.0, "token_id": "...", "closed": true,
          "question": "Will the highest temperature in ..." },
        ...
    ] }

Settlement row (canonical schema):
    settlement_id, target_date, condition_id, market_id, bracket, token_id,
    final_price, settlement_status

Files with `null` content or empty `brackets` are skipped (genuine upstream
gaps). For each bracket, condition_id and market_id are looked up from the
`signals` table by (city, target_date, bracket) -- the same market the
strategy was trading. Settlements with no signal row get `condition_id=NULL`
and won't join in queries; this is acceptable for brackets the strategy
never touched.

Idempotent: re-running is safe.

Run:
    python -m weather_dashboard.ingest.pm_history_settlements --db-path runtime/weather.db
    python -m weather_dashboard.ingest.pm_history_settlements --db-path runtime/weather.db --pmh-dir <path>
"""
from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path
from typing import Iterable

from src.strategies.weather_edge_v1.ids import make_settlement_id

DEFAULT_PMH_DIR = "runtime/weather_edge_v1/market_data/cache/pm_history"


def _settlement_id(
    target_date: str,
    condition_id: str | None,
    market_id: str | None,
    bracket: str,
) -> str:
    if condition_id and market_id:
        # Keep the same natural ID as legacy_migration.research_csv so a
        # pm_history backfill does not duplicate an already-migrated settlement.
        return make_settlement_id(
            target_date=target_date,
            condition_id=condition_id,
            market_id=market_id,
            bracket=bracket,
        )
    raw = f"pm_history_settlement|{target_date}|{condition_id or ''}|{market_id or ''}|{bracket}"
    import hashlib
    return hashlib.sha256(raw.encode()).hexdigest()


def _binary_final_price(final_price) -> float | None:
    """Normalize Polymarket near-binary settlement prices.

    Some pm_history files store resolved brackets as 0.9995 / 0.0005 while
    the downstream settlement contract expects binary 1.0 / 0.0.
    """
    try:
        value = float(final_price)
    except (TypeError, ValueError):
        return None
    if value >= 0.99:
        return 1.0
    if value <= 0.01:
        return 0.0
    return None


def _settlement_status(final_price) -> str:
    if _binary_final_price(final_price) is not None:
        return "settled"
    return "missing_bracket"


def _parse_filename(name: str) -> tuple[str, str] | None:
    """`Beijing_2026-05-20.json` -> ('Beijing', '2026-05-20'). Skips others."""
    base = name[:-5] if name.endswith(".json") else name
    if base.startswith("prices_") or "_2026-" not in base:
        return None
    if len(base) < 11 or base[-11] != "_":
        return None
    return base[:-11], base[-10:]


def _signal_lookup_map(conn: sqlite3.Connection) -> dict[tuple, tuple[str, str]]:
    """(city, target_date, bracket) -> (condition_id, market_id) from signals.
    Brackets the strategy never touched won't be in this map; their settlement
    is still written but with NULL condition_id.
    """
    out: dict[tuple, tuple[str, str]] = {}
    for r in conn.execute(
        "SELECT DISTINCT city, target_date, bracket, condition_id, market_id "
        "FROM signals WHERE condition_id IS NOT NULL"
    ):
        out[(r["city"], r["target_date"], str(r["bracket"]))] = (
            r["condition_id"], r["market_id"]
        )
    return out


def ingest(conn: sqlite3.Connection, pmh_dir: str, *, dry_run: bool = False) -> dict:
    conn.row_factory = sqlite3.Row
    sig_lookup = _signal_lookup_map(conn)
    files = sorted(Path(pmh_dir).glob("*_2026-*.json"))

    stats = {
        "files_seen": 0, "files_skipped_null": 0,
        "brackets_seen": 0, "settlements_inserted": 0,
        "no_signal_match": 0, "dry_run": dry_run,
    }

    for f in files:
        parsed = _parse_filename(f.name)
        if parsed is None:
            continue
        city, date = parsed
        stats["files_seen"] += 1
        try:
            d = json.load(open(f))
        except Exception:
            stats["files_skipped_null"] += 1
            continue
        if not isinstance(d, dict) or not d.get("brackets"):
            stats["files_skipped_null"] += 1
            continue

        for b in d["brackets"]:
            label = str(b.get("label"))
            final_price = b.get("final_price")
            token_id = str(b.get("token_id") or "") or None
            if final_price is None:
                continue
            stats["brackets_seen"] += 1
            condition_id, market_id = sig_lookup.get((city, date, label), (None, None))
            if condition_id is None:
                stats["no_signal_match"] += 1
            sid = _settlement_id(date, condition_id, market_id, label)
            normalized_final_price = _binary_final_price(final_price)
            stored_final_price = normalized_final_price if normalized_final_price is not None else float(final_price)
            status = _settlement_status(final_price)

            if dry_run:
                continue
            cur = conn.execute(
                """INSERT OR IGNORE INTO settlements
                   (settlement_id, target_date, condition_id, market_id, bracket,
                    token_id, final_price, settlement_status)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (sid, date, condition_id, market_id, label, token_id,
                 stored_final_price, status),
            )
            stats["settlements_inserted"] += cur.rowcount or 0

    if not dry_run:
        conn.commit()
    return stats


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db-path", default="runtime/weather.db")
    ap.add_argument("--pmh-dir", default=DEFAULT_PMH_DIR)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    conn = sqlite3.connect(args.db_path)
    try:
        out = ingest(conn, args.pmh_dir, dry_run=args.dry_run)
        print(json.dumps(out, indent=2))
    finally:
        conn.close()


if __name__ == "__main__":
    main()
