"""Version and metadata contracts for weather feature frames."""

from __future__ import annotations

FEATURE_FRAME_SCHEMA_VERSION = "feature_frame_v1"
WEATHER_STATE_VERSION = "weather_state_v4"
WEATHER_REGIME_VERSION = "weather_regime_v2"
WEATHER_BIAS_VERSION = "weather_bias_v1"
MARKET_GEOMETRY_VERSION = "market_geometry_v1"
EXECUTION_FEATURE_VERSION = "execution_features_v1"

PIT_PROVENANCE_LIVE_CAPTURE = "live_capture"
PIT_PROVENANCE_ARCHIVE_RECONSTRUCTION = "archive_reconstruction"
PIT_PROVENANCE_VALUES = {
    PIT_PROVENANCE_LIVE_CAPTURE,
    PIT_PROVENANCE_ARCHIVE_RECONSTRUCTION,
}

DEFAULT_FEATURE_VERSION_MANIFEST = {
    "weather_state": WEATHER_STATE_VERSION,
    "weather_regime": WEATHER_REGIME_VERSION,
    "weather_bias": WEATHER_BIAS_VERSION,
    "market_geometry": MARKET_GEOMETRY_VERSION,
    "execution_features": EXECUTION_FEATURE_VERSION,
}

FEATURE_FRAME_REQUIRED_METADATA = (
    "feature_schema_version",
    "feature_grain",
    "as_of_ts_utc",
    "source_profile_id",
    "feature_version_manifest",
    "pit_provenance",
    "builder_version",
    "input_snapshot_id",
)

UNIT_SPACE_F = "F"
UNIT_SPACE_NATIVE = "native"

FIELD_UNIT_CONTRACT = {
    "temp_trend_1h_f": UNIT_SPACE_F,
    "temp_trend_3h_f": UNIT_SPACE_F,
    "temp_trend_report_anchored_1h_f": UNIT_SPACE_F,
    "temp_trend_report_anchored_3h_f": UNIT_SPACE_F,
    "dewpoint_depression_f": UNIT_SPACE_F,
    "current_temp_native": UNIT_SPACE_NATIVE,
    "running_max_native": UNIT_SPACE_NATIVE,
    "decline_from_running_max_native": UNIT_SPACE_NATIVE,
    "forecast_gap_to_running_native": UNIT_SPACE_NATIVE,
    "bracket_distance_native": UNIT_SPACE_NATIVE,
    "wind_dir_deg": "degree",
    "wind_speed_kt": "knot",
    "wind_dir_1h_prior_deg": "degree",
    "wind_dir_change_1h_deg": "degree",
    "dewpoint_change_1h_f": UNIT_SPACE_F,
    "dewpoint_trend_1h_f": UNIT_SPACE_F,
    "dewpoint_trend_3h_f": UNIT_SPACE_F,
    "dewpoint_trend_report_anchored_1h_f": UNIT_SPACE_F,
    "dewpoint_trend_report_anchored_3h_f": UNIT_SPACE_F,
    "relative_humidity_trend_report_anchored_3h_pct": "percent",
    "lowest_cloud_base_ft_agl": "foot_agl",
    "ceiling_ft_agl": "foot_agl",
    "obs_age_minutes": "minute",
    "expected_report_cadence": "minute",
    "solar_elevation_deg": "degree",
    "daylight_remaining_minutes": "minute",
    "forecast_precip_probability_to_peak_max_pct": "percent",
    "forecast_precip_probability_remaining_3h_max_pct": "percent",
    "forecast_cloud_cover_remaining_3h_mean_pct": "percent",
    "forecast_wind_speed_remaining_3h_max_kt": "knot",
    "forecast_wind_direction_remaining_3h_mean_deg": "degree",
    "forecast_precip_probability_future_3h_max_pct": "percent",
    "forecast_cloud_cover_future_3h_mean_pct": "percent",
    "forecast_wind_speed_future_3h_max_kt": "knot",
    "forecast_wind_direction_future_3h_mean_deg": "degree",
    "observation_history_span_minutes": "minute",
    "minutes_since_first_running_max": "minute",
    "minutes_since_last_running_max": "minute",
    "minutes_since_last_strict_new_high": "minute",
    "clear_sky_regime_minutes": "minute",
    "clear_sky_regime_temp_change_f": UNIT_SPACE_F,
    "precip_free_regime_minutes": "minute",
    "precip_free_regime_temp_change_f": UNIT_SPACE_F,
    "minutes_since_last_precip_obs": "minute",
    "forecast_temperature_at_decision_f": UNIT_SPACE_F,
    "forecast_temperature_innovation_f": UNIT_SPACE_F,
    "forecast_temperature_innovation_native": UNIT_SPACE_NATIVE,
    "forecast_remaining_max_f": UNIT_SPACE_F,
    "forecast_remaining_temp_delta_f": UNIT_SPACE_F,
    "forecast_reheat_after_now_f": UNIT_SPACE_F,
    "forecast_remaining_peak_hour_local": "hour_local",
    "forecast_remaining_gap_to_running_native": UNIT_SPACE_NATIVE,
    "forecast_remaining_gap_to_current_native": UNIT_SPACE_NATIVE,
    "transition_window_minutes": "minute",
    "transition_probability": "probability",
    "minutes_to_transition_window_start": "minute",
    "minutes_to_transition_window_end": "minute",
    "transition_timing_offset_minutes": "minute",
    "transition_window_elapsed_fraction": "ratio",
    "transition_hazard_score": "score_0_1",
    "transition_timing_uncertainty_score": "score_0_1",
    "transition_exposure_score": "score_0_1",
    "transition_temperature_impact_weight": "score_0_1",
    "temperature_transition_risk_score": "score_0_1",
    "regime_predictability_score": "score_0_1",
}

WEATHER_PHYSICAL_FEATURE_FIELDS = (
    "precip_state",
    "precip_intensity_code",
    "present_weather_codes",
    "cloud_layer_count",
    "lowest_cloud_base_ft_agl",
    "ceiling_ft_agl",
    "cloud_cover_change_1h_code",
    "wind_dir_deg",
    "wind_dir_sin",
    "wind_dir_cos",
    "wind_speed_change_1h_kt",
    "wind_dir_1h_prior_deg",
    "wind_dir_change_1h_deg",
    "dewpoint_change_1h_f",
    "dewpoint_trend_1h_f",
    "dewpoint_trend_3h_f",
    "temp_trend_report_anchored_1h_f",
    "temp_trend_report_anchored_3h_f",
    "dewpoint_trend_report_anchored_1h_f",
    "dewpoint_trend_report_anchored_3h_f",
    "relative_humidity_trend_report_anchored_3h_pct",
    "relative_humidity_change_1h_pct",
    "observation_history_span_minutes",
    "first_running_max_obs_utc",
    "last_running_max_obs_utc",
    "minutes_since_first_running_max",
    "minutes_since_last_running_max",
    "minutes_since_last_strict_new_high",
    "same_running_max_obs_count",
    "running_max_clock_left_censored",
    "clear_sky_regime_minutes",
    "clear_sky_regime_temp_change_f",
    "clear_sky_regime_left_censored",
    "precip_free_regime_minutes",
    "precip_free_regime_temp_change_f",
    "precip_free_regime_left_censored",
    "first_precip_obs_utc",
    "last_precip_obs_utc",
    "precip_obs_count",
    "first_thunderstorm_obs_utc",
    "last_thunderstorm_obs_utc",
    "thunderstorm_obs_count",
    "precip_onset_clock_source",
    "thunderstorm_onset_clock_source",
    "minutes_since_last_precip_obs",
    "obs_age_minutes",
    "expected_report_cadence",
    "obs_cadence_ratio",
    "minutes_to_next_expected_obs",
    "source_latency_minutes",
    "solar_elevation_deg",
    "solar_elevation_2h_deg",
    "solar_elevation_delta_2h_deg",
    "daylight_remaining_minutes",
    "solar_heating_potential",
    "forecast_precip_probability_to_peak_max_pct",
    "forecast_cloud_cover_to_peak_mean_pct",
    "forecast_wind_speed_to_peak_max_kt",
    "forecast_wind_direction_to_peak_mean_deg",
    "forecast_remaining_3h_status",
    "forecast_remaining_3h_hour_count",
    "forecast_precip_probability_remaining_3h_max_pct",
    "forecast_cloud_cover_remaining_3h_mean_pct",
    "forecast_wind_speed_remaining_3h_max_kt",
    "forecast_wind_direction_remaining_3h_mean_deg",
    "forecast_future_3h_status",
    "forecast_future_3h_hour_count",
    "forecast_precip_probability_future_3h_max_pct",
    "forecast_cloud_cover_future_3h_mean_pct",
    "forecast_wind_speed_future_3h_max_kt",
    "forecast_wind_direction_future_3h_mean_deg",
    "forecast_temperature_at_decision_f",
    "forecast_temperature_innovation_status",
    "forecast_temperature_innovation_f",
    "forecast_temperature_innovation_native",
    "forecast_remaining_max_f",
    "forecast_remaining_temp_delta_f",
    "forecast_reheat_after_now_f",
    "forecast_remaining_peak_hour_local",
    "forecast_remaining_gap_to_running_native",
    "forecast_remaining_gap_to_current_native",
    "taf_transition_available",
    "taf_transition_coverage_status",
    "transition_window_count",
    "transition_event_types",
    "transition_change_type",
    "transition_window_start_utc",
    "transition_window_end_utc",
    "transition_window_minutes",
    "transition_probability",
    "minutes_to_transition_window_start",
    "minutes_to_transition_window_end",
    "transition_timing_state",
    "transition_timing_offset_minutes",
    "transition_window_elapsed_fraction",
    "transition_hazard_score",
    "transition_timing_uncertainty_score",
    "transition_exposure_score",
    "transition_temperature_impact_weight",
    "temperature_transition_risk_score",
    "regime_predictability_score",
    "taf_issue_time_utc",
    "taf_first_seen_utc",
    "taf_valid_from_utc",
    "taf_valid_to_utc",
    "taf_issue_age_minutes",
    "taf_capture_age_minutes",
    "taf_validity_state",
)
