"""Constants for PAP state machine."""

STATUS_NEW = "NEW"
STATUS_IGNORED = "IGNORED"
STATUS_EXPIRED = "EXPIRED"
STATUS_READY_TO_PARSE = "READY_TO_PARSE"
STATUS_PARSED = "PARSED"
STATUS_READY_TO_SEARCH = "READY_TO_SEARCH"
STATUS_INVESTIGATED = "INVESTIGATED"
STATUS_READY_FOR_DECISION = "READY_FOR_DECISION"

DEFAULT_LIQUIDITY_THRESHOLD = 5000.0
DEFAULT_PRICE_MIN = 0.05
DEFAULT_PRICE_MAX = 0.95
DEFAULT_MIN_QUESTION_LEN = 0
DEFAULT_MIN_RULES_LEN = 0
DEFAULT_MIN_DESCRIPTION_LEN = 0
DEFAULT_READY_SCORE = 60
DEFAULT_EDGE_THRESHOLD = 0.15
DEFAULT_IGNORE_CATEGORIES = {"Sports", "Gaming"}
