#!/usr/bin/env python3
"""Train the PIT-compatible Amsterdam remaining-heat V8 weather model.

Model selection is confined to target dates ending on 2025-12-31.  August
2026 is deliberately absent from this program: it is scored by the separate
frozen-forward replay after the artifact and policy manifest are written.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pickle
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from weather_modeling.knmi_10m_path import add_knmi_10m_path_features
from weather_modeling.solar_geometry import add_solar_geometry_features
from weather_modeling.forecast_path import (
    FORECAST_PATH_FEATURES,
    add_fixed_lead_forecast_path_features,
)


DEFAULT_DATASET = Path(
    "/Volumes/jrs/weather_data_feed_service_runtime/research/"
    "amsterdam_knmi_10m_remaining_heat_v1/weather_checkpoints.csv.gz"
)
DEFAULT_OUTPUT_ROOT = Path(
    "/Volumes/jrs/weather_data_feed_service_runtime/research/model_runs/"
    "amsterdam_knmi_remaining_heat_v8"
)
TRAIN_END = "2025-12-31"
EPS = 1e-7

# Every column is generated by the deployed Amsterdam adapter from information
# available at the KNMI first-seen checkpoint.  Forecast curves intentionally
# remain outside V8 until a same-source historical/live contract exists.
FEATURES = [
    "day_of_year_sin", "day_of_year_cos", "time_sin", "time_cos",
    "official_running_max_c", "current_bracket_c", "d1_bracket_c",
    "ta_c", "tx_c", "knmi_ta_running_max_c", "knmi_tx_running_max_c",
    "distance_to_d1_c", "tx_distance_to_d1_c",
    "decline_from_running_max_c", "minutes_since_running_max", "tx_minus_ta_c",
    "ta_delta_10m_c", "ta_delta_20m_c", "ta_delta_30m_c", "ta_delta_60m_c",
    "ta_delta_120m_c", "ta_trend_accel_20m_c", "ta_range_60m_c",
    "max_positive_ta_step_60m_c", "minutes_since_new_high",
    "plateau_duration_minutes", "knmi_drawdown_from_high_c",
    "rebound_from_60m_low_c", "is_rebounding_after_pullback",
    "cadence_complete_20m", "cadence_complete_30m", "cadence_complete_60m",
    "cadence_complete_120m", "solar_w_m2", "solar_delta_30m",
    "solar_delta_60m", "solar_energy_60m_mj_m2", "cloud_okta",
    "cloud_delta_30m", "cloud_delta_60m", "cloud_mean_60m_okta",
    "precip_mm_h", "precip_delta_30m", "precip_delta_60m", "rain_present",
    "rain_minutes_60m", "humidity_pct", "humidity_delta_30m",
    "humidity_delta_60m", "dewpoint_c", "wind_speed_mps", "wind_gust_mps",
    "wind_direction_sin", "wind_direction_cos", "pressure_hpa",
    "latest_official_temp_c", "official_report_age_minutes",
    "knmi_ta_minus_latest_official_c", "knmi_tx_minus_latest_official_c",
    "knmi_ta_minus_official_running_max_c",
    "knmi_tx_minus_official_running_max_c", "source_above_official_d1",
    "source_above_official_d1_persistence_rows", "source_gap_minutes",
    "solar_elevation_geometry_deg", "solar_elevation_positive",
    "remaining_clear_sky_integral_h", "daylight_remaining_geometry_minutes",
    "minutes_from_solar_noon", "instant_solar_efficiency",
    "remaining_solar_per_plateau", "remaining_solar_per_drawdown",
    "pressure_delta_180m", "pressure_delta_360m", "wind_speed_delta_180m",
    "dewpoint_delta_180m", "humidity_delta_180m", "cloud_mean_180m_okta",
    "cadence_complete_180m", "cadence_complete_360m",
]

PARAMETERS = [
    {"learning_rate": 0.035, "max_iter": 220, "max_leaf_nodes": 15,
     "min_samples_leaf": 75, "l2_regularization": 3.0},
    {"learning_rate": 0.025, "max_iter": 300, "max_leaf_nodes": 15,
     "min_samples_leaf": 100, "l2_regularization": 4.0},
    {"learning_rate": 0.03, "max_iter": 260, "max_leaf_nodes": 31,
     "min_samples_leaf": 125, "l2_regularization": 5.0},
]

FOLDS = [
    ("2021-07-30", "2022-12-31", "2023-01-01", "2023-12-31"),
    ("2021-07-30", "2023-12-31", "2024-01-01", "2024-12-31"),
    ("2021-07-30", "2024-12-31", "2025-01-01", "2025-12-31"),
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def model(parameters: dict[str, Any]) -> HistGradientBoostingClassifier:
    return HistGradientBoostingClassifier(
        **parameters, early_stopping=False, random_state=20260812
    )


def date_equal_weights(frame: pd.DataFrame) -> np.ndarray:
    counts = frame.groupby("target_date")["target_date"].transform("size")
    return 1.0 / counts.to_numpy(float)


def matrix(frame: pd.DataFrame, features: list[str]) -> pd.DataFrame:
    return frame.loc[:, features].apply(pd.to_numeric, errors="coerce")


def prepare(path: Path, forecast_path: Path | None = None) -> tuple[pd.DataFrame, list[str]]:
    frame = pd.read_csv(path)
    frame = frame[frame["target_date"].astype(str).le(TRAIN_END)].copy()
    frame = add_knmi_10m_path_features(frame)
    frame = add_solar_geometry_features(frame)
    features = list(FEATURES)
    if forecast_path is not None:
        forecast = pd.read_csv(forecast_path)
        frame = add_fixed_lead_forecast_path_features(frame, forecast)
        frame = frame[frame["target_date"].astype(str).ge(str(forecast["target_date"].astype(str).min()))].copy()
        features.extend(FORECAST_PATH_FEATURES)
    missing = sorted(set(features) - set(frame.columns))
    if missing:
        raise ValueError(f"training feature contract incomplete: {missing}")
    frame["label"] = frame["label_d1_cross_eod"].astype(int)
    local_minute = pd.to_numeric(frame["decision_minute_local"], errors="coerce")
    frame["active_12_16"] = local_minute.between(12 * 60, 16 * 60)
    return frame, features


def losses(rows: pd.DataFrame, probability: np.ndarray) -> dict[str, float]:
    scored = rows[["target_date", "label"]].copy()
    scored["p"] = np.clip(probability, EPS, 1 - EPS)
    scored["brier"] = (scored["p"] - scored["label"]) ** 2
    scored["logloss"] = -(
        scored["label"] * np.log(scored["p"])
        + (1 - scored["label"]) * np.log(1 - scored["p"])
    )
    daily = scored.groupby("target_date")[["brier", "logloss"]].mean()
    return {
        "rows": int(len(rows)),
        "target_dates": int(rows["target_date"].nunique()),
        "brier": float(daily["brier"].mean()),
        "logloss": float(daily["logloss"].mean()),
        "accuracy_0_5": float(
            ((scored["p"] >= 0.5) == scored["label"].astype(bool)).mean()
        ),
    }


def objective(rows: pd.DataFrame, probability: np.ndarray) -> float:
    full = losses(rows, probability)
    active_mask = rows["active_12_16"].to_numpy(bool)
    active = losses(rows.loc[active_mask], probability[active_mask])
    return full["brier"] + 0.20 * full["logloss"] + 2.0 * (
        active["brier"] + 0.20 * active["logloss"]
    )


def oof(frame: pd.DataFrame, parameters: dict[str, Any], features: list[str]) -> pd.DataFrame:
    parts: list[pd.DataFrame] = []
    for fold, (train_start, train_end, test_start, test_end) in enumerate(FOLDS):
        train = frame[frame["target_date"].between(train_start, train_end)]
        test = frame[frame["target_date"].between(test_start, test_end)]
        if train.empty or test.empty:
            continue
        estimator = model(parameters)
        estimator.fit(matrix(train, features), train["label"], sample_weight=date_equal_weights(train))
        part = test[["target_date", "observed_at_utc", "decision_minute_local",
                     "active_12_16", "label", "weather_checkpoint_key"]].copy()
        part["p_raw"] = np.clip(estimator.predict_proba(matrix(test, features))[:, 1], EPS, 1 - EPS)
        part["fold"] = fold
        parts.append(part)
    if not parts:
        raise ValueError("no non-empty expanding OOF folds")
    return pd.concat(parts, ignore_index=True)


def fit_calibrator(rows: pd.DataFrame) -> LogisticRegression:
    probability = np.clip(rows["p_raw"].to_numpy(float), EPS, 1 - EPS)
    logit = np.log(probability / (1 - probability)).reshape(-1, 1)
    calibrator = LogisticRegression(C=0.1, max_iter=2000, random_state=20260812)
    calibrator.fit(logit, rows["label"], sample_weight=date_equal_weights(rows))
    return calibrator


def calibrate(calibrator: LogisticRegression, probability: np.ndarray) -> np.ndarray:
    value = np.clip(probability, EPS, 1 - EPS)
    return calibrator.predict_proba(np.log(value / (1 - value)).reshape(-1, 1))[:, 1]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--forecast-path", type=Path, default=None)
    parser.add_argument("--model-id", default="amsterdam_knmi_remaining_heat_v8")
    args = parser.parse_args()
    frame, features = prepare(args.dataset, args.forecast_path)
    candidates: list[dict[str, Any]] = []
    for index, parameters in enumerate(PARAMETERS):
        predictions = oof(frame, parameters, features)
        candidates.append({
            "index": index,
            "parameters": parameters,
            "objective_raw": objective(predictions, predictions["p_raw"].to_numpy(float)),
            "predictions": predictions,
        })
    selected = min(candidates, key=lambda row: row["objective_raw"])
    predictions = selected["predictions"]
    calibrator = fit_calibrator(predictions)
    predictions["p_calibrated"] = calibrate(calibrator, predictions["p_raw"].to_numpy(float))
    use_calibration = objective(predictions, predictions["p_calibrated"].to_numpy(float)) < selected["objective_raw"]
    predictions["p_selected"] = predictions[
        "p_calibrated" if use_calibration else "p_raw"
    ]

    final = model(selected["parameters"])
    final.fit(matrix(frame, features), frame["label"], sample_weight=date_equal_weights(frame))
    identity = {
        "dataset_sha256": sha256(args.dataset),
        "forecast_dataset_sha256": (
            sha256(args.forecast_path) if args.forecast_path is not None else None
        ),
        "script_sha256": sha256(Path(__file__)),
        "train_end": TRAIN_END,
        "model_id": args.model_id,
        "feature_contract_sha256": hashlib.sha256(
            json.dumps(features, separators=(",", ":")).encode()
        ).hexdigest(),
    }
    run_id = hashlib.sha256(json.dumps(identity, sort_keys=True).encode()).hexdigest()[:16]
    output = args.output_root / f"run={run_id}"
    output.mkdir(parents=True, exist_ok=True)
    artifact_schema = (
        "amsterdam_knmi_remaining_heat_model_v9"
        if args.forecast_path is not None
        else "amsterdam_knmi_remaining_heat_model_v8"
    )
    artifact_path = output / ("model_v9.pkl" if args.forecast_path is not None else "model_v8.pkl")
    artifact = {
        "schema_version": artifact_schema,
        "model_id": args.model_id,
        "artifact_train_end": TRAIN_END,
        "frozen_validation_start": "2026-08-01",
        "target": "P(final EHAM bracket leaves current exact bracket upward)",
        "features": features,
        "feature_semantics": (
            "KNMI/official-state/solar-geometry plus immutable ECMWF previous-day1 curve"
            if args.forecast_path is not None
            else "KNMI/official-state/solar-geometry PIT-compatible; no forecast model mixing"
        ),
        "estimator": final,
        "calibrator": calibrator if use_calibration else None,
        "parameters": selected["parameters"],
        "identity": identity,
    }
    with artifact_path.open("wb") as handle:
        pickle.dump(artifact, handle)
    predictions.to_csv(output / "oof_predictions_2023_2025.csv.gz", index=False, compression="gzip")
    summary = {
        "schema_version": "amsterdam_knmi_remaining_heat_training_v8",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "run_id": run_id,
        "model_id": args.model_id,
        "artifact_path": str(artifact_path),
        "artifact_sha256": sha256(artifact_path),
        "training_rows": int(len(frame)),
        "training_dates": int(frame["target_date"].nunique()),
        "training_range": [str(frame["target_date"].min()), str(frame["target_date"].max())],
        "feature_count": len(features),
        "forecast_path": str(args.forecast_path) if args.forecast_path else None,
        "selected_parameters": selected["parameters"],
        "calibration_selected": use_calibration,
        "oof_all": losses(predictions, predictions["p_selected"].to_numpy(float)),
        "oof_active_12_16": losses(
            predictions[predictions["active_12_16"]],
            predictions.loc[predictions["active_12_16"], "p_selected"].to_numpy(float),
        ),
        "candidate_objectives": [
            {key: value for key, value in row.items() if key != "predictions"}
            for row in candidates
        ],
        "identity": identity,
        "frozen_validation_read": False,
    }
    (output / "metrics.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
