"""PIT contract corpus and legal-role mapping for disputed markets."""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from typing import Any


BULLETIN_RE = re.compile(
    r"updates made by the question creator via the bulletin board at\s+"
    r"(0x[a-fA-F0-9]{40})",
    re.IGNORECASE,
)
ADDITIONAL_CONTEXT_RE = re.compile(r"\badditional\s+context\b", re.IGNORECASE)
GENERATED_NONBINDING_RE = re.compile(
    r"(?:experimental|ai[- ]generated|generated by ai).{0,120}"
    r"(?:does not|doesn't|will not).{0,80}(?:resolution|resolve)",
    re.IGNORECASE | re.DOTALL,
)
OPERATIONAL_NOTICE_RE = re.compile(
    r"(?is)^we(?:'|’)?re aware of the dispute.*if a clarification"
)
CONTRACT_CORRECTION_RE = re.compile(
    r"(?i)(rules? (?:has|have) been updated|title corrected|"
    r"trades? prior to .* (?:will be )?refunded|updated to reflect (?:its|the) title)"
)


def classify_official_update_text(text: str) -> str:
    """Separate adjudicative text from operations and contract repair."""
    if OPERATIONAL_NOTICE_RE.search(text):
        return "operational_notice"
    if CONTRACT_CORRECTION_RE.search(text):
        return "contract_correction_or_refund"
    return "adjudication_guidance"


def normalized_contract_text(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip().casefold()


def extract_ancillary_description(text: str) -> str:
    """Extract the description embedded in Polymarket YES_OR_NO ancillary data."""
    match = re.search(
        r"(?is)q:\s*title:\s*.*?,\s*description:\s*(.*?)"
        r"(?:,?\s*market[_ ]?id\s*[:=]\s*\d+|;marketId:\s*\d+)",
        str(text or ""),
    )
    return re.sub(r"\s+", " ", match.group(1)).strip(" ,") if match else ""


def bulletin_adapter_from_ancillary(text: str) -> str | None:
    match = BULLETIN_RE.search(str(text or ""))
    return match.group(1).lower() if match else None


def _fragment(
    *,
    origin: str,
    legal_role: str,
    text: str,
    observed_at_utc: str,
    effective_at_utc: str | None = None,
    publisher: str | None = None,
    adjudication_use: str = "binding",
) -> dict[str, Any]:
    content = str(text or "").strip()
    digest = hashlib.sha256(content.encode()).hexdigest()
    return {
        "fragment_id": hashlib.sha256(f"{origin}|{digest}".encode()).hexdigest()[:24],
        "origin": origin,
        "legal_role": legal_role,
        "text": content,
        "content_sha256": digest,
        "observed_at_utc": observed_at_utc,
        "effective_at_utc": effective_at_utc,
        "publisher": publisher,
        "adjudication_use": adjudication_use,
        "pit_eligible": True,
    }


def build_contract_corpus(
    *,
    ancillary_text: str,
    market: dict[str, Any],
    observed_at_utc: str,
    observed_at_ts: int,
    bulletin: dict[str, Any] | None = None,
    bulletin_error: str | None = None,
) -> dict[str, Any]:
    """Build a legally stratified, point-in-time corpus.

    Bulletin updates are not silently treated as binding outcomes.  They are
    official interpretive inputs, but each case still needs an assessment that
    the update clarifies rather than changes the question's fundamental intent.
    """
    ancillary_description = extract_ancillary_description(ancillary_text)
    gamma_description = str(market.get("description") or market.get("rules") or "").strip()
    bulletin_adapter = bulletin_adapter_from_ancillary(ancillary_text)
    fragments = [
        _fragment(
            origin="uma_ancillary_data",
            legal_role="binding_request",
            text=ancillary_text,
            observed_at_utc=observed_at_utc,
        )
    ]
    if ancillary_description:
        fragments.append(
            _fragment(
                origin="uma_ancillary_description",
                legal_role="binding_resolution_rule",
                text=ancillary_description,
                observed_at_utc=observed_at_utc,
            )
        )
    if gamma_description:
        generated = bool(GENERATED_NONBINDING_RE.search(gamma_description))
        matches = bool(
            ancillary_description
            and normalized_contract_text(gamma_description)
            == normalized_contract_text(ancillary_description)
        )
        fragments.append(
            _fragment(
                origin="gamma_market_description",
                legal_role=(
                    "generated_summary_nonbinding"
                    if generated
                    else "binding_resolution_rule_mirror"
                    if matches
                    else "platform_description_revision"
                ),
                text=gamma_description,
                observed_at_utc=observed_at_utc,
                effective_at_utc=str(market.get("updatedAt") or "") or None,
                adjudication_use="excluded" if generated else "binding" if matches else "review_required",
            )
        )

    valid_updates: list[dict[str, Any]] = []
    future_updates: list[dict[str, Any]] = []
    if bulletin:
        for update in bulletin.get("updates") or []:
            target = valid_updates if int(update.get("timestamp") or 0) <= observed_at_ts else future_updates
            target.append(update)
        for update in valid_updates:
            update_text = str(update.get("text") or "")
            update_class = classify_official_update_text(update_text)
            fragments.append(
                _fragment(
                    origin="uma_ctf_adapter_bulletin",
                    legal_role=(
                        "platform_operational_notice"
                        if update_class == "operational_notice"
                        else "contract_correction_or_refund"
                        if update_class == "contract_correction_or_refund"
                        else "onchain_clarification"
                    ),
                    text=update_text,
                    observed_at_utc=observed_at_utc,
                    effective_at_utc=datetime.fromtimestamp(
                        int(update.get("timestamp") or 0), timezone.utc
                    ).isoformat(),
                    publisher=str(update.get("publisher") or bulletin.get("creator") or ""),
                    adjudication_use=(
                        "excluded"
                        if update_class == "operational_notice"
                        else "review_required"
                    ),
                )
            )

    gamma_matches = bool(
        ancillary_description
        and normalized_contract_text(gamma_description)
        == normalized_contract_text(ancillary_description)
    )
    ancillary_parity = None
    if bulletin and bulletin.get("ancillary_text") is not None:
        ancillary_parity = normalized_contract_text(bulletin["ancillary_text"]) == normalized_contract_text(ancillary_text)
    blockers: list[str] = []
    if bulletin_adapter and bulletin_error:
        blockers.append("bulletin_updates_unavailable")
    if ancillary_parity is False:
        blockers.append("subgraph_ancillary_differs_from_adapter_question")
    if bulletin and bulletin_adapter and str(bulletin.get("adapter") or "").lower() != bulletin_adapter:
        blockers.append("request_bulletin_adapter_mismatch")
    if gamma_description and ancillary_description and not gamma_matches:
        blockers.append("gamma_description_differs_from_onchain_request")
    guidance_updates = [
        update
        for update in valid_updates
        if classify_official_update_text(str(update.get("text") or ""))
        == "adjudication_guidance"
    ]
    operational_updates = [
        update
        for update in valid_updates
        if classify_official_update_text(str(update.get("text") or ""))
        == "operational_notice"
    ]
    correction_updates = [
        update
        for update in valid_updates
        if classify_official_update_text(str(update.get("text") or ""))
        == "contract_correction_or_refund"
    ]
    if guidance_updates:
        blockers.append("official_clarification_requires_fundamental_intent_review")
    if correction_updates:
        blockers.append("official_contract_correction_or_refund_requires_precedence_review")
    if gamma_description and ADDITIONAL_CONTEXT_RE.search(gamma_description) and not valid_updates:
        blockers.append("gamma_additional_context_not_verified_onchain")

    binding_map = {
        "bulletin_enabled_by_request": bool(bulletin_adapter),
        "bulletin_adapter": bulletin_adapter,
        "bulletin_fetch_error": bulletin_error,
        "adapter_question_creator": bulletin.get("creator") if bulletin else None,
        "adapter_ancillary_matches_subgraph": ancillary_parity,
        "gamma_description_matches_ancillary": gamma_matches,
        "official_update_count_as_of_snapshot": len(valid_updates),
        "official_adjudication_guidance_count_as_of_snapshot": len(guidance_updates),
        "official_operational_notice_count_as_of_snapshot": len(operational_updates),
        "official_contract_correction_count_as_of_snapshot": len(correction_updates),
        "future_update_count_excluded": len(future_updates),
        "adjudication_blockers": blockers,
        "deterministic_verdict_allowed": not blockers,
        "interpretive_review_required": bool(blockers),
    }
    corpus_basis = {
        "fragments": [
            {
                key: fragment.get(key)
                for key in (
                    "origin",
                    "legal_role",
                    "content_sha256",
                    "effective_at_utc",
                    "publisher",
                    "adjudication_use",
                )
            }
            for fragment in fragments
        ],
        # Keep the adjudicative identity stable when diagnostic counters are
        # added.  Fragment hashes and blockers already capture material update
        # text/classification changes.
        "binding_map": {
            key: binding_map.get(key)
            for key in (
                "bulletin_enabled_by_request",
                "bulletin_adapter",
                "bulletin_fetch_error",
                "adapter_question_creator",
                "adapter_ancillary_matches_subgraph",
                "gamma_description_matches_ancillary",
                "official_update_count_as_of_snapshot",
                "future_update_count_excluded",
                "adjudication_blockers",
                "deterministic_verdict_allowed",
                "interpretive_review_required",
            )
        },
    }
    return {
        "schema_version": "dispute_contract_corpus_v1",
        "as_of_utc": observed_at_utc,
        "fragments": fragments,
        "binding_map": binding_map,
        "contract_corpus_sha256": hashlib.sha256(
            json.dumps(corpus_basis, sort_keys=True).encode()
        ).hexdigest(),
    }


def build_dispute_thesis(snapshot: dict[str, Any]) -> dict[str, Any]:
    issue = snapshot.get("issue_features") or {}
    mechanism = str(issue.get("mechanism") or "")
    track = str(issue.get("track") or "insufficient")
    dimensions: list[str] = []
    dimension_map = {
        "sports_stat_scope": ["stat_scope", "period_scope", "official_finality"],
        "sports_result_scope": ["result_scope", "remake_or_forfeit", "official_finality"],
        "speech_or_social_count": ["verb_definition", "speaker_or_entity", "evidence_threshold"],
        "general_semantic_boundary": ["definition_boundary", "evidence_threshold"],
        "event_occurrence_boundary": ["event_definition", "effective_time", "credible_reporting"],
        "financial_touch_range_source": ["transaction_definition", "entity_scope", "source_hierarchy"],
    }
    dimensions.extend(dimension_map.get(mechanism, [mechanism] if mechanism else []))
    corpus = snapshot.get("contract_corpus") or {}
    verdict = snapshot.get("rule_verdict") or {}
    proposed_binary = snapshot.get("proposal", {}).get("proposed_binary")
    outcomes = list(snapshot.get("outcomes") or [])
    # UMA YES_OR_NO uses 0 = NO and 1 = YES.  Gamma normally exposes the
    # corresponding token outcomes as ["Yes", "No"], so the array index is
    # the inverse of the UMA binary value.
    proposed_outcome = outcomes[1 - proposed_binary] if proposed_binary in (0, 1) and len(outcomes) == 2 else None
    winning_outcome = verdict.get("winning_outcome") if verdict.get("status") == "verified" else None
    relation = None
    if winning_outcome is not None and proposed_outcome is not None:
        relation = "proposal" if winning_outcome == proposed_outcome else "reverse"
    return {
        "schema_version": "dispute_thesis_v1",
        "track": "deterministic" if track == "mechanical" else "interpretive",
        "mechanism": mechanism,
        "contested_dimensions": dimensions,
        "proposed_outcome": proposed_outcome,
        "winning_outcome": winning_outcome,
        "winning_relation_to_proposal": relation,
        "material_adjudication_divergence": relation == "reverse" if relation else None,
        "contract_corpus_sha256": corpus.get("contract_corpus_sha256"),
        "contract_blockers": list(corpus.get("binding_map", {}).get("adjudication_blockers") or []),
        "status": "proved" if winning_outcome is not None else "requires_adjudication",
    }
