"""Shared weather data primitives used by collectors, research, and strategies."""

from weather_data_feed.city_calendar import (
    CITY_TIMEZONE,
    city_local_datetime,
    city_local_date,
    city_scan_dates,
    city_timezone_name,
    local_settle_utc,
    parse_now_utc,
    station_timezone,
    timezone_label,
    unique_city_scan_dates,
)
from weather_data_feed.market_brackets import bracket_contains, parse_label_dict, parse_market_bracket
from weather_data_feed.forecast_sources import (
    OPEN_METEO_CONTEXT_DAILY_FIELDS,
    OPEN_METEO_CONTEXT_HOURLY_FIELDS,
    OPEN_METEO_FORECAST_RUN_HOURLY_FIELDS,
    OPEN_METEO_HISTORICAL_FORECAST_API,
    OPEN_METEO_MULTI_MODEL_ORDER,
    OPEN_METEO_MULTI_MODEL_SPECS,
    OPEN_METEO_SINGLE_RUN_API,
    OPEN_METEO_SINGLE_RUN_MODEL_MIN_DATE,
    ForecastFetchResult,
    ForecastFetchSettings,
    build_taf_signal,
    build_vertical_profile_signal,
    fetch_aviationweather_taf,
    fetch_open_meteo_historical_forecast,
    fetch_open_meteo_multi_model,
    fetch_open_meteo_previous_runs,
    fetch_open_meteo_single_run,
    fetch_open_meteo_weather_context,
    target_day_hourly_summary,
)
from weather_data_feed.forecast_enrichment_cache import (
    FORECAST_ENRICHMENT_SCHEMA_VERSION,
    forecast_enrichment_records,
    index_forecast_enrichment,
    load_forecast_enrichment,
    load_indexed_forecast_enrichment,
    normalize_forecast_enrichment_record,
)
from weather_data_feed.models import (
    CityConfig,
    CrossingEvent,
    MarketDateContext,
    MarketSnapshotRecord,
    ObservationRecord,
    RunningMaxState,
    SourceProfile,
)
from weather_data_feed.observation_cache import (
    OBSERVATION_CACHE_SCHEMA_VERSION,
    build_observation_cache,
    index_observation_cache,
    load_observation_cache,
    normalize_observation_cache_record,
    write_observation_cache,
)
from weather_data_feed.observation_clock import ObservationClockConfig, observation_clock_guard
from weather_data_feed.runway_sources import (
    AMSC_AWOS_AIRPORTS,
    AMOS_AIRPORTS,
    RunwayFetchResult,
    RunwayFetchSettings,
    fetch_amos_runway,
    fetch_amsc_awos_runway,
    parse_amos_runway_html,
    parse_amsc_wind_plate_payload,
    supported_runway_cities,
)
from weather_data_feed.snapshot_protocol import (
    SNAPSHOT_SCHEMA_VERSION,
    market_snapshot_record,
    normalize_snapshot_record,
    parse_market_event_date,
    validate_snapshot_record,
)
from weather_data_feed.source_policy import build_city_policy, load_city_configs
from weather_data_feed.source_registry import load_source_profiles, source_profile_for_city

__all__ = [
    "CITY_TIMEZONE",
    "CityConfig",
    "CrossingEvent",
    "MarketDateContext",
    "MarketSnapshotRecord",
    "OBSERVATION_CACHE_SCHEMA_VERSION",
    "OPEN_METEO_CONTEXT_DAILY_FIELDS",
    "OPEN_METEO_CONTEXT_HOURLY_FIELDS",
    "OPEN_METEO_FORECAST_RUN_HOURLY_FIELDS",
    "OPEN_METEO_HISTORICAL_FORECAST_API",
    "OPEN_METEO_MULTI_MODEL_ORDER",
    "OPEN_METEO_MULTI_MODEL_SPECS",
    "OPEN_METEO_SINGLE_RUN_API",
    "OPEN_METEO_SINGLE_RUN_MODEL_MIN_DATE",
    "ObservationClockConfig",
    "ObservationRecord",
    "AMSC_AWOS_AIRPORTS",
    "AMOS_AIRPORTS",
    "RunwayFetchResult",
    "RunwayFetchSettings",
    "RunningMaxState",
    "SNAPSHOT_SCHEMA_VERSION",
    "SourceProfile",
    "ForecastFetchResult",
    "ForecastFetchSettings",
    "FORECAST_ENRICHMENT_SCHEMA_VERSION",
    "bracket_contains",
    "build_city_policy",
    "build_observation_cache",
    "build_taf_signal",
    "build_vertical_profile_signal",
    "city_local_datetime",
    "city_local_date",
    "city_scan_dates",
    "city_timezone_name",
    "fetch_aviationweather_taf",
    "fetch_open_meteo_historical_forecast",
    "fetch_open_meteo_multi_model",
    "fetch_open_meteo_previous_runs",
    "fetch_open_meteo_single_run",
    "fetch_open_meteo_weather_context",
    "fetch_amos_runway",
    "fetch_amsc_awos_runway",
    "forecast_enrichment_records",
    "index_forecast_enrichment",
    "index_observation_cache",
    "load_city_configs",
    "load_forecast_enrichment",
    "load_indexed_forecast_enrichment",
    "load_observation_cache",
    "load_source_profiles",
    "market_snapshot_record",
    "normalize_forecast_enrichment_record",
    "normalize_observation_cache_record",
    "normalize_snapshot_record",
    "observation_clock_guard",
    "parse_label_dict",
    "parse_market_event_date",
    "parse_market_bracket",
    "local_settle_utc",
    "parse_now_utc",
    "parse_amos_runway_html",
    "parse_amsc_wind_plate_payload",
    "source_profile_for_city",
    "station_timezone",
    "supported_runway_cities",
    "target_day_hourly_summary",
    "timezone_label",
    "unique_city_scan_dates",
    "validate_snapshot_record",
    "write_observation_cache",
]
